# Location of top-level MicroPython directory
MPY_DIR = ../../..

# Name of module
MOD = curve25519

# Source files (.c or .py)
SRC = memset.c curve25519.c upy.c


# Architecture to build for (x86, x64, armv7m, xtensa, xtensawin)
#ARCH = x64
ARCH = xtensawin

# Include to get the rules for compiling and linking the module
include $(MPY_DIR)/py/dynruntime.mk
