# Location of top-level MicroPython directory
MPY_DIR = ../../..

# Name of module
MOD = features1

# Source files (.c or .py)
SRC =  memset.c orlp/src/add_scalar.c  orlp/src/ge.c            orlp/src/keypair.c  orlp/src/seed.c    orlp/src/sign.c orlp/src/fe.c          orlp/src/key_exchange.c  orlp/src/sc.c       orlp/src/sha512.c  orlp/src/verify.c features1.c


# Architecture to build for (x86, x64, armv7m, xtensa, xtensawin)
#ARCH = x64
ARCH = xtensawin

# Include to get the rules for compiling and linking the module
include $(MPY_DIR)/py/dynruntime.mk
